language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby
before_script:
  - RABBITMQ_CONFIG_FILE=spec/assets/rabbitmq rabbitmq-server &
  - sleep 3
notifications:
  irc:
    - "irc.freenode.net#sensu"
